## renderの挙動確認

In [3]:
import sys
sys.path.append('../')

In [7]:
from tasks.lidar import *
import open3d as o3d
import numpy as np

In [8]:
pcd_file = '../scene/rellis-3d/0/pointcloud/0.pcd'

pcd = o3d.io.read_point_cloud(pcd_file)
pcd = np.asarray(pcd.points)
pcd = torch.from_numpy(pcd).float().to('cpu')

In [16]:
pcd[:2]

tensor([[ 9.5962,  0.5113, -1.3273],
        [ 8.6473, -0.4903, -1.2646]])

In [15]:
render.pcd2ray(pcd[:2])

(tensor([[ 0.0000,  0.0000,  0.0000, -0.0533,  0.1383,  1.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0567,  0.1462,  1.0000]]),
 tensor([[9.5962],
         [8.6473]]))